blank_issues_enabled: true
contact_links:
  - name: "An issue or feature request related to the GUI"
    url: https://github.com/bitcoin-core/gui/issues/new
    about: Any report, issue or feature request related to the GUI should be reported in 'bitcoin-core/gui' repository which is used exclusively for the development of the GUI.