name: Create single commit

on:
  push:
    branches:
      - master
      - feature/add-gtest

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VBK_FORK_COMMIT: 8830cb58abc888144a1edb9b2fba427716cc45d8
      VBK_SQUASHED_BRANCH: veriblock
    steps:
      - uses: actions/checkout@v1
      - name: Create local changes
        run: git reset --soft ${VBK_FORK_COMMIT}
      - name: Commit files
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git branch -D ${VBK_SQUASHED_BRANCH}
            git checkout -b ${VBK_SQUASHED_BRANCH}
            git commit -m "Auto squash commits to master" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}