name: Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


    jobs:
      build:
    
        runs-on: windows-latest
        
        steps:
    
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Install dependencies
          run: |
            wsl apt-get update
            wsl apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git g++-mingw-w64-x86-64
            wsl sudo update-alternatives --config x86_64-w64-mingw32-g++
    
        - name: Build
          run: |
            wsl PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g')
            wsl sudo bash -c "echo 0 > /proc/sys/fs/binfmt_misc/status"
            wsl cd depends
            wsl make HOST=x86_64-w64-mingw32
            wsl cd ..
            wsl ./autogen.sh
            wsl CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
            wsl make check